[sdl]
fullscreen=false
output=metal
vsync=true

[dosbox]
language=
machine=svga_s3
captures=captures
memsize=64

[render]
frameskip=1
aspect=true
scaler=none

[cpu]
core=normal
cputype=auto
cycles=auto
cycleup=10
cycledown=20

[mixer]
nosound=false
rate=44100
blocksize=2048
prebuffer=25

[midi]
mpu401=intelligent
mididevice=none

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5
sbmixer=true
oplmode=auto
oplemu=default
oplrate=44100

[gus]
gus=false

[speaker]
pcspeaker=true
pcrate=44100
tandy=off
tandyrate=44100
disney=false

[dos]
xms=true
ems=true
umb=true
keyboardlayout=none

[autoexec]
# fdk2/ folder must be placed in the app's Documents via Finder file sharing.
mount c fdk2
imgmount d fdk2/CD/FDPS_1.cue fdk2/CD/FDPS_2.cue -t cdrom
c:
FDPS.EXE
